#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

eval "$(direnv hook zsh)"

# added by travis gem
[ -f /Users/benjaminmorris/.travis/travis.sh ] && source /Users/benjaminmorris/.travis/travis.sh
